language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: fpxZ26Fqw60KO0LBcy9fKCXJZiJnNjN7tvKiSUEh67sAsPkxLgWTG9ucxkA2cWopwLvRKJLQj0HgQn+KNJ7+mB1a4CL6BzQwRacB+vcTntGhekUjTzfjCzFirNKMGDmFBT1I5qdzXMaOHBqFxa7LSUjplJ3dsXyGKarc8ErZ+Xs=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: OuIaGTgtox6IIaE6unD1YEuIRMIRMoNBoXUqEjHDIjSHBz/zl3Cc3XX/SRfFaTIcTpWhKavDghGEPm9+53aX0jwzu/jEqnl2gZBpfTOJzVAipEqq56kp2kkRh4RGotQQbEx10/e2bFhlVrqIk6k3cFQRUOQCb0+X1CAKK+uQ5jU=
sudo: false
